name: Build SEA [Windows]

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build SEA Executable
        uses: bryopsida/node-sea-action@v1
        with:
          input: http.js
          node-version: 22

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: http-sea-exe
          path: http.exe
